export default function fileType(ext) {
  switch (ext) {
    case "jpg":
    case "jpeg":
    case "jfif":
    case "png":
    case "exif":
    case "tiff":
    case "giv":
    case "bmp":
    case "ppm":
    case "pgm":
    case "pbm":
    case "pnm":
    case "webp":
    case "hdr":
    case "heif":
    case "img":
    case "ico":
    case "eps":
    case "raw":
      return "image";
    case "webm":
    case "mkv":
    case "flv":
    case "vob":
    case "ogv":
    case "ogg":
    case "rrc":
    case "gifv":
    case "mng":
    case "mov":
    case "avi":
    case "qt":
    case "wmv":
    case "yuv":
    case "rm":
    case "asf":
    case "amv":
    case "mp4":
    case "m4p":
    case "m4v":
    case "mpg":
    case "mp2":
    case "mpeg":
    case "mpe":
    case "mpv":
    case "m4v":
    case "svi":
    case "3gp":
    case "3g2":
    case "mxf":
    case "roq":
    case "nsv":
    case "flv":
    case "f4v":
    case "f4p":
    case "f4a":
    case "f4b":
      return "video";
    case "file":
    case "txt":
    case "json":
    case "html":
    case "xhtml":
    case "htm":
    case "js":
    case "jsx":
    case "ini":
    case "java":
    case "jsh":
    case "kt":
    case "md":
    case "env":
    case "ts":
    case "tsx":
    case "sh":
    case "abnf":
    case "accesslog":
    case "actionscript":
    case "ada":
    case "angelscript":
    case "apache":
    case "applescript":
    case "arcade":
    case "arduino":
    case "armasm":
    case "asciidoc":
    case "aspectj":
    case "autohotkey":
    case "autoit":
    case "avrasm":
    case "awk":
    case "axapta":
    case "bash":
    case "basic":
    case "bnf":
    case "brainfuck":
    case "c":
    case "cal":
    case "capnproto":
    case "ceylon":
    case "clean":
    case "clojure":
    case "cmake":
    case "coffeescript":
    case "coq":
    case "cos":
    case "cpp":
    case "crmsh":
    case "crystal":
    case "csharp":
    case "csp":
    case "css":
    case "d":
    case "dart":
    case "delphi":
    case "diff":
    case "django":
    case "dns":
    case "dockerfile":
    case "dos":
    case "dsconfig":
    case "dts":
    case "dust":
    case "ebnf":
    case "elixir":
    case "elm":
    case "erb":
    case "erlang":
    case "excel":
    case "fix":
    case "flix":
    case "fortran":
    case "fsharp":
    case "gams":
    case "gauss":
    case "gcode":
    case "gherkin":
    case "glsl":
    case "gml":
    case "go":
    case "golo":
    case "gradle":
    case "groovy":
    case "haml":
    case "handlebars":
    case "haskell":
    case "haxe":
    case "hsp":
    case "htmlbars":
    case "http":
    case "hy":
    case "inform7":
    case "ini":
    case "irpf90":
    case "isbl":
    case "javascript":
    case "json":
    case "julia":
    case "kotlin":
    case "lasso":
    case "latex":
    case "ldif":
    case "leaf":
    case "less":
    case "lisp":
    case "livecodeserver":
    case "livescript":
    case "llvm":
    case "lsl":
    case "lua":
    case "makefile":
    case "markdown":
    case "mathematica":
    case "matlab":
    case "maxima":
    case "mel":
    case "mercury":
    case "mipsasm":
    case "mizar":
    case "mojolicious":
    case "monkey":
    case "moonscript":
    case "n1ql":
    case "nginx":
    case "nim":
    case "nix":
    case "nsis":
    case "objectivec":
    case "ocaml":
    case "openscad":
    case "oxygene":
    case "parser3":
    case "perl":
    case "pf":
    case "pgsql":
    case "php":
    case "plaintext":
    case "pony":
    case "powershell":
    case "processing":
    case "profile":
    case "prolog":
    case "properties":
    case "protobuf":
    case "puppet":
    case "purebasic":
    case "python":
    case "q":
    case "qml":
    case "r":
    case "reasonml":
    case "rib":
    case "roboconf":
    case "routeros":
    case "rsl":
    case "ruby":
    case "ruleslanguage":
    case "rust":
    case "sas":
    case "scala":
    case "scheme":
    case "scilab":
    case "scss":
    case "shell":
    case "smali":
    case "smalltalk":
    case "sml":
    case "sqf":
    case "sql":
    case "stan":
    case "stata":
    case "step21":
    case "stylus":
    case "subunit":
    case "swift":
    case "taggerscript":
    case "tap":
    case "tcl":
    case "thrift":
    case "tp":
    case "twig":
    case "typescript":
    case "vala":
    case "vbnet":
    case "vbscript":
    case "verilog":
    case "vhdl":
    case "vim":
    case "x86asm":
    case "xl":
    case "xml":
    case "xquery":
    case "yaml":
    case "zephir":
      return "text";
    default:
      return "other";
  }
}
